# Generated by Django 2.0.7 on 2018-10-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Roll', models.CharField(max_length=15)),
                ('Contact', models.CharField(max_length=10)),
                ('Available', models.BooleanField(default=0)),
            ],
        ),
    ]
